export async function createTablePdf(data,regularBytes,boldBytes){
 const {PDFDocument,rgb}=globalThis.PDFLib,doc=await PDFDocument.create();doc.registerFontkit(globalThis.fontkit);const font=await doc.embedFont(regularBytes,{subset:true}),bold=await doc.embedFont(boldBytes,{subset:true});const W=841.89,H=595.28,m=28,pages=[],table=data.table;
 const text=v=>String(v??'').replace(/[\u0000-\u001f]/g,' ').replace(/\s+/g,' ').trim();
 function wrap(v,width,size,f=font){const out=[];let line='';for(const c of text(v)){if(f.widthOfTextAtSize(line+c,size)>width&&line){out.push(line);line=c;}else line+=c;}if(line)out.push(line);return out.length?out:[''];}
 const blocks=[];if(table.columns.length<=8)blocks.push(table.columns);else{blocks.push(table.columns.slice(0,8));for(let i=8;i<table.columns.length;i+=7)blocks.push([table.columns[0],...table.columns.slice(i,i+7)]);}let page,y;
 function newPage(cols,block){page=doc.addPage([W,H]);pages.push(page);const dispatch=data.type==='Daily Dispatch';page.drawRectangle({x:m,y:H-67,width:W-2*m,height:39,color:dispatch?rgb(.12,.31,.47):rgb(.33,.51,.21)});page.drawText('STARISH AUTOPAC - '+text(data.type),{x:m+9,y:H-47,size:14,font:bold,color:rgb(1,1,1)});page.drawText(data.from+' to '+data.to+' | '+data.shift+' | Table '+(block+1)+'/'+blocks.length,{x:m,y:H-82,size:9,font});y=H-101;if(dispatch)drawDispatchSummary();drawRow(cols,Object.fromEntries(cols.map(k=>[k,k])),true);}
 function drawDispatchSummary(){const records=data.reports||[],vehicles=new Set(records.map(r=>text(r.fields?.['Vehicle Number']||r.fields?.Vehicle)).filter(Boolean)),qty=records.reduce((a,r)=>a+(Number(r.fields?.Quantity)||0),0),amount=records.reduce((a,r)=>a+(Number(r.fields?.['Amount (Rs)'])||0),0),nfmt=n=>new Intl.NumberFormat('en-IN',{maximumFractionDigits:0}).format(n),labels=['Total Vehicles','Total Invoices','Total Qty','Total Amount (Rs)'],values=[nfmt(vehicles.size),nfmt(records.length),nfmt(qty),nfmt(amount)],w=(W-2*m)/4,h=34;for(let i=0;i<4;i++){const x=m+i*w;page.drawRectangle({x,y:y-h,width:w,height:h,color:rgb(.85,.89,.95),borderColor:rgb(.67,.72,.78),borderWidth:.5});page.drawRectangle({x,y:y-13,width:w,height:13,color:rgb(.12,.31,.47)});page.drawText(labels[i],{x:x+5,y:y-9,size:7,font:bold,color:rgb(1,1,1)});page.drawText(values[i],{x:x+5,y:y-27,size:10,font:bold,color:rgb(.08,.16,.25)});}y-=h+10;}
 function drawRow(cols,row,header=false,total=false){const widths=cols.map(k=>W/cols.length-2*m/cols.length),lines=cols.map((k,i)=>wrap(row[k],widths[i]-12,9,header||total?bold:font));const maxLines=Math.max(...lines.map(a=>a.length));if(!header&&maxLines>25){for(let start=0;start<maxLines;start+=25){const part={};cols.forEach((k,i)=>part[k]=lines[i].slice(start,start+25).join(''));drawRow(cols,part,false,total);}return;}const height=maxLines*12+12;if(y-height<42&&!header)newPage(cols,blocks.indexOf(cols));let x=m;cols.forEach((k,i)=>{page.drawRectangle({x,y:y-height,width:widths[i],height,color:header||total?rgb(.87,.93,.82):rgb(1,1,1),borderColor:rgb(.67,.72,.64),borderWidth:.5});lines[i].forEach((line,j)=>page.drawText(line,{x:x+6,y:y-13-j*12,size:9,font:header||total?bold:font,color:rgb(.08,.16,.08)}));x+=widths[i];});y-=height;}
 for(let b=0;b<blocks.length;b++){const cols=blocks[b];newPage(cols,b);if(!table.rows.length)drawRow(cols,{[cols[0]]:'No records'});for(const row of table.rows)drawRow(cols,row.values);if(table.totals)drawRow(cols,table.totals,false,true);}
 pages.forEach((p,i)=>p.drawText('Starish | '+data.from+' to '+data.to+' | Page '+(i+1)+' of '+pages.length,{x:m,y:22,size:8,font}));doc.setTitle(data.type+' '+data.from+' to '+data.to);return doc.save();
}
